/*HEADER****************************************************************
************************************************************************
***
*** Copyright (c) 2004 ARC International
*** All rights reserved
***
*** This software embodies materials and concepts which are
*** confidential to ARC International and is made available solely
*** pursuant to the terms of a written license agreement with
*** ARC International.
***
*** Comments:  This file was generated by postmosy.
***
*** $Project:RTCS$
*** $Header:mqxmib.c, 3, 2/12/2004 9:48:47 AM, Ricky Charlet$
***
************************************************************************

$Log:
 3    RTCS      1.2         2/12/2004 9:48:47 AM   Ricky Charlet   CR#1461:
      added .c files to support codewarrior builds. Add these files to your
      codewarrior project.
 2    RTCS      1.1         2/12/2004 9:46:01 AM   Ricky Charlet   no CR#: 
      Second try to get keyword expansion going.
 1    RTCS      1.0         2/12/2004 9:37:52 AM   Ricky Charlet   
$

***  $NoKeywords$
************************************************************************
*END*******************************************************************/

#include <rtcsrtos.h>
#include <rtcs.h>
#include <rtcs_prv.h>
#include "snmpcfg.h"
#include "asn1.h"
#include "snmp.h"

extern RTCSMIB_NODE MIBNODE_enterprises;

extern RTCSMIB_NODE MIBNODE_mqxIOCLAPB;
extern RTCSMIB_NODE MIBNODE_mqxTaskFlagWatchdogEnabled;
extern RTCSMIB_NODE MIBNODE_mqxTaskIOstderr;
extern RTCSMIB_NODE MIBNODE_mqxConfigPspFPRegisters;
extern RTCSMIB_NODE MIBNODE_mqxConfig64BitInts;
extern RTCSMIB_NODE MIBNODE_mqxConfigCheckAlloc;
extern RTCSMIB_NODE MIBNODE_mqxIOCPPP;
extern RTCSMIB_NODE MIBNODE_mqxComponentPart;
extern RTCSMIB_NODE MIBNODE_mqxTaskStackUsed;
extern RTCSMIB_NODE MIBNODE_mqxTaskTable;
extern RTCSMIB_NODE MIBNODE_mqxTask;
extern RTCSMIB_NODE MIBNODE_mqxConfigComponentDestruction;
extern RTCSMIB_NODE MIBNODE_mqxConfigKernelLogging;
extern RTCSMIB_NODE MIBNODE_mqxCPU;
extern RTCSMIB_NODE MIBNODE_mqxKernel;
extern RTCSMIB_NODE MIBNODE_mqxIOCENET;
extern RTCSMIB_NODE MIBNODE_mqxIOCLAPD;
extern RTCSMIB_NODE MIBNODE_mqxComponentSem;
extern RTCSMIB_NODE MIBNODE_mqxTaskFlagPreemptionDisabled;
extern RTCSMIB_NODE MIBNODE_mqxTaskIOstdin;
extern RTCSMIB_NODE MIBNODE_mqxTaskSchedHomePriority;
extern RTCSMIB_NODE MIBNODE_mqxTaskName;
extern RTCSMIB_NODE MIBNODE_mqxConfigTaskDestruction;
extern RTCSMIB_NODE MIBNODE_mqxCPUEndian;
extern RTCSMIB_NODE MIBNODE_mqxComponentEDS;
extern RTCSMIB_NODE MIBNODE_mqxComponentQlog;
extern RTCSMIB_NODE MIBNODE_mqxTaskIOstdout;
extern RTCSMIB_NODE MIBNODE_mqxIOCHDLC;
extern RTCSMIB_NODE MIBNODE_mqxTaskFlagFloatingPoint;
extern RTCSMIB_NODE MIBNODE_mqxTaskStackSize;
extern RTCSMIB_NODE MIBNODE_mqxTaskSchedTimeSlice;
extern RTCSMIB_NODE MIBNODE_mqxConfigInlineMacros;
extern RTCSMIB_NODE MIBNODE_mqxDate;
extern RTCSMIB_NODE MIBNODE_mqxIOCMFS;
extern RTCSMIB_NODE MIBNODE_mqxComponentTimer;
extern RTCSMIB_NODE MIBNODE_mqxComponent;
extern RTCSMIB_NODE MIBNODE_mqxConfigCheckValidity;
extern RTCSMIB_NODE MIBNODE_mqxCopyright;
extern RTCSMIB_NODE MIBNODE_mqxComponentIPC;
extern RTCSMIB_NODE MIBNODE_mqxComponentMutex;
extern RTCSMIB_NODE MIBNODE_mqxTaskIO;
extern RTCSMIB_NODE MIBNODE_mqxTaskSchedPriority;
extern RTCSMIB_NODE MIBNODE_mqxTaskCreator;
extern RTCSMIB_NODE MIBNODE_mqxConfig32BitQIDs;
extern RTCSMIB_NODE MIBNODE_mqxConfigPspKernelLogging;
extern RTCSMIB_NODE MIBNODE_mqxConfigTaskCreationBlocks;
extern RTCSMIB_NODE MIBNODE_mqxConfig;
extern RTCSMIB_NODE MIBNODE_mqxRevBSP;
extern RTCSMIB_NODE MIBNODE_mqxIOCSNMP;
extern RTCSMIB_NODE MIBNODE_mqxTaskFlagLoggingEnabled;
extern RTCSMIB_NODE MIBNODE_mqxConfigMonitorStack;
extern RTCSMIB_NODE MIBNODE_mqxProcessorNum;
extern RTCSMIB_NODE MIBNODE_mqxIOCSDLC;
extern RTCSMIB_NODE MIBNODE_mqxTaskSched;
extern RTCSMIB_NODE MIBNODE_mqxTaskID;
extern RTCSMIB_NODE MIBNODE_mqxCPUType;
extern RTCSMIB_NODE MIBNODE_mqxRevKernel;
extern RTCSMIB_NODE MIBNODE_mqxVersion;
extern RTCSMIB_NODE MIBNODE_psti;
extern RTCSMIB_NODE MIBNODE_mqxTaskState;
extern RTCSMIB_NODE MIBNODE_mqxIOCCAN;
extern RTCSMIB_NODE MIBNODE_mqxComponentLog;
extern RTCSMIB_NODE MIBNODE_mqxTaskFlag;
extern RTCSMIB_NODE MIBNODE_mqxTaskEntry;
extern RTCSMIB_NODE MIBNODE_mqxConfigCheckErrors;
extern RTCSMIB_NODE MIBNODE_mqxIOCRTCS;
extern RTCSMIB_NODE MIBNODE_mqxTaskSchedPolicy;
extern RTCSMIB_NODE MIBNODE_mqxTaskErrorCode;
extern RTCSMIB_NODE MIBNODE_mqxConfigFloatingPointIO;
extern RTCSMIB_NODE MIBNODE_mqxCPUAddressing;
extern RTCSMIB_NODE MIBNODE_mqxRevPSP;
extern RTCSMIB_NODE MIBNODE_mqxRevision;
extern RTCSMIB_NODE MIBNODE_mqx;
extern RTCSMIB_NODE MIBNODE_mqxIOCIO;
extern RTCSMIB_NODE MIBNODE_mqxIOC;
extern RTCSMIB_NODE MIBNODE_mqxComponentMessage;
extern RTCSMIB_NODE MIBNODE_mqxComponentWatchdog;
extern RTCSMIB_NODE MIBNODE_mqxComponentEvent;
extern RTCSMIB_NODE MIBNODE_mqxComponentName;
extern RTCSMIB_NODE MIBNODE_mqxRevIO;

boolean MIB_find_mqxTaskEntry        (uint_32, pointer, pointer _PTR_);

boolean MIB_instance_mqxTaskEntry        (RTCSMIB_WALK_PTR, uint_32, boolean (_CODE_PTR_)(uint_32, pointer, pointer _PTR_), boolean _PTR_, pointer _PTR_);


RTCSMIB_NODE MIBNODE_mqxIOCLAPB = {
   3,

   &MIBNODE_mqxIOCLAPD,
   NULL,
   &MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskFlagWatchdogEnabled = {
   3,

   &MIBNODE_mqxTaskFlagPreemptionDisabled,
   NULL,
   &MIBNODE_mqxTaskFlag,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskIOstderr = {
   3,

   NULL,
   NULL,
   &MIBNODE_mqxTaskIO,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_OCTET,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxConfigPspFPRegisters = {
   13,

   &MIBNODE_mqxConfig32BitQIDs,
   NULL,
   &MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxConfig64BitInts = {
   11,

   &MIBNODE_mqxConfigPspKernelLogging,
   NULL,
   &MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxConfigCheckAlloc = {
   10,

   &MIBNODE_mqxConfig64BitInts,
   NULL,
   &MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxIOCPPP = {
   9,

   &MIBNODE_mqxIOCSNMP,
   NULL,
   &MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxComponentPart = {
   9,

   &MIBNODE_mqxComponentIPC,
   NULL,
   &MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskStackUsed = {
   8,

   &MIBNODE_mqxTaskIO,
   NULL,
   &MIBNODE_mqxTaskEntry,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskTable = {
   1,

   NULL,
   &MIBNODE_mqxTaskEntry,
   &MIBNODE_mqxTask,

   0,
   NULL,
   MIB_instance_zero, ASN1_TYPE_SEQUENCE,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxTask = {
   2,

   &MIBNODE_mqxComponent,
   &MIBNODE_mqxTaskTable,
   &MIBNODE_mqx,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxConfigComponentDestruction = {
   7,

   &MIBNODE_mqxConfigCheckErrors,
   NULL,
   &MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxConfigKernelLogging = {
   3,

   &MIBNODE_mqxConfigMonitorStack,
   NULL,
   &MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxCPU = {
   5,

   &MIBNODE_mqxProcessorNum,
   &MIBNODE_mqxCPUType,
   &MIBNODE_mqxKernel,

   0,
   NULL,
   MIB_instance_zero, ASN1_TYPE_SEQUENCE,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxKernel = {
   1,

   &MIBNODE_mqxTask,
   &MIBNODE_mqxVersion,
   &MIBNODE_mqx,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxIOCENET = {
   11,

   NULL,
   NULL,
   &MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxIOCLAPD = {
   4,

   &MIBNODE_mqxIOCSDLC,
   NULL,
   &MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxComponentSem = {
   2,

   &MIBNODE_mqxComponentEvent,
   NULL,
   &MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskFlagPreemptionDisabled = {
   4,

   NULL,
   NULL,
   &MIBNODE_mqxTaskFlag,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskIOstdin = {
   1,

   &MIBNODE_mqxTaskIOstdout,
   NULL,
   &MIBNODE_mqxTaskIO,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_OCTET,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskSchedHomePriority = {
   2,

   &MIBNODE_mqxTaskSchedPolicy,
   NULL,
   &MIBNODE_mqxTaskSched,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskName = {
   3,

   &MIBNODE_mqxTaskState,
   NULL,
   &MIBNODE_mqxTaskEntry,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_OCTET,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxConfigTaskDestruction = {
   6,

   &MIBNODE_mqxConfigComponentDestruction,
   NULL,
   &MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxCPUEndian = {
   2,

   &MIBNODE_mqxCPUAddressing,
   NULL,
   &MIBNODE_mqxCPU,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxComponentEDS = {
   12,

   NULL,
   NULL,
   &MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxComponentQlog = {
   11,

   &MIBNODE_mqxComponentEDS,
   NULL,
   &MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskIOstdout = {
   2,

   &MIBNODE_mqxTaskIOstderr,
   NULL,
   &MIBNODE_mqxTaskIO,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_OCTET,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxIOCHDLC = {
   6,

   &MIBNODE_mqxIOCMFS,
   NULL,
   &MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskFlagFloatingPoint = {
   1,

   &MIBNODE_mqxTaskFlagLoggingEnabled,
   NULL,
   &MIBNODE_mqxTaskFlag,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskStackSize = {
   7,

   &MIBNODE_mqxTaskStackUsed,
   NULL,
   &MIBNODE_mqxTaskEntry,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskSchedTimeSlice = {
   4,

   NULL,
   NULL,
   &MIBNODE_mqxTaskSched,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxConfigInlineMacros = {
   2,

   &MIBNODE_mqxConfigKernelLogging,
   NULL,
   &MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxDate = {
   4,

   &MIBNODE_mqxCPU,
   NULL,
   &MIBNODE_mqxKernel,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_OCTET,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxIOCMFS = {
   7,

   &MIBNODE_mqxIOCCAN,
   NULL,
   &MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxComponentTimer = {
   5,

   &MIBNODE_mqxComponentLog,
   NULL,
   &MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxComponent = {
   3,

   &MIBNODE_mqxIOC,
   &MIBNODE_mqxComponentName,
   &MIBNODE_mqx,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxConfigCheckValidity = {
   9,

   &MIBNODE_mqxConfigCheckAlloc,
   NULL,
   &MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxCopyright = {
   3,

   &MIBNODE_mqxDate,
   NULL,
   &MIBNODE_mqxKernel,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_OCTET,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxComponentIPC = {
   10,

   &MIBNODE_mqxComponentQlog,
   NULL,
   &MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxComponentMutex = {
   4,

   &MIBNODE_mqxComponentTimer,
   NULL,
   &MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskIO = {
   9,

   &MIBNODE_mqxTaskFlag,
   &MIBNODE_mqxTaskIOstdin,
   &MIBNODE_mqxTaskEntry,

   0,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_SEQUENCE,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskSchedPriority = {
   1,

   &MIBNODE_mqxTaskSchedHomePriority,
   NULL,
   &MIBNODE_mqxTaskSched,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskCreator = {
   2,

   &MIBNODE_mqxTaskName,
   NULL,
   &MIBNODE_mqxTaskEntry,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxConfig32BitQIDs = {
   14,

   NULL,
   NULL,
   &MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxConfigPspKernelLogging = {
   12,

   &MIBNODE_mqxConfigPspFPRegisters,
   NULL,
   &MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxConfigTaskCreationBlocks = {
   5,

   &MIBNODE_mqxConfigTaskDestruction,
   NULL,
   &MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxConfig = {
   7,

   NULL,
   &MIBNODE_mqxConfigFloatingPointIO,
   &MIBNODE_mqxKernel,

   0,
   NULL,
   MIB_instance_zero, ASN1_TYPE_SEQUENCE,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxRevBSP = {
   4,

   NULL,
   NULL,
   &MIBNODE_mqxRevision,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxIOCSNMP = {
   10,

   &MIBNODE_mqxIOCENET,
   NULL,
   &MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskFlagLoggingEnabled = {
   2,

   &MIBNODE_mqxTaskFlagWatchdogEnabled,
   NULL,
   &MIBNODE_mqxTaskFlag,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxConfigMonitorStack = {
   4,

   &MIBNODE_mqxConfigTaskCreationBlocks,
   NULL,
   &MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxProcessorNum = {
   6,

   &MIBNODE_mqxConfig,
   NULL,
   &MIBNODE_mqxKernel,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxIOCSDLC = {
   5,

   &MIBNODE_mqxIOCHDLC,
   NULL,
   &MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskSched = {
   6,

   &MIBNODE_mqxTaskStackSize,
   &MIBNODE_mqxTaskSchedPriority,
   &MIBNODE_mqxTaskEntry,

   0,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_SEQUENCE,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskID = {
   1,

   &MIBNODE_mqxTaskCreator,
   NULL,
   &MIBNODE_mqxTaskEntry,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxCPUType = {
   1,

   &MIBNODE_mqxCPUEndian,
   NULL,
   &MIBNODE_mqxCPU,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxRevKernel = {
   1,

   &MIBNODE_mqxRevPSP,
   NULL,
   &MIBNODE_mqxRevision,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxVersion = {
   1,

   &MIBNODE_mqxRevision,
   NULL,
   &MIBNODE_mqxKernel,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_psti = {
   4653,

   NULL,
   &MIBNODE_mqx,
   &MIBNODE_enterprises,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskState = {
   4,

   &MIBNODE_mqxTaskErrorCode,
   NULL,
   &MIBNODE_mqxTaskEntry,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxIOCCAN = {
   8,

   &MIBNODE_mqxIOCPPP,
   NULL,
   &MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxComponentLog = {
   6,

   &MIBNODE_mqxComponentWatchdog,
   NULL,
   &MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskFlag = {
   10,

   NULL,
   &MIBNODE_mqxTaskFlagFloatingPoint,
   &MIBNODE_mqxTaskEntry,

   0,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_SEQUENCE,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskEntry = {
   1,

   NULL,
   &MIBNODE_mqxTaskID,
   &MIBNODE_mqxTaskTable,

   0,
   MIB_find_mqxTaskEntry,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_SEQUENCE,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxConfigCheckErrors = {
   8,

   &MIBNODE_mqxConfigCheckValidity,
   NULL,
   &MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxIOCRTCS = {
   2,

   &MIBNODE_mqxIOCLAPB,
   NULL,
   &MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskSchedPolicy = {
   3,

   &MIBNODE_mqxTaskSchedTimeSlice,
   NULL,
   &MIBNODE_mqxTaskSched,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxTaskErrorCode = {
   5,

   &MIBNODE_mqxTaskSched,
   NULL,
   &MIBNODE_mqxTaskEntry,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxConfigFloatingPointIO = {
   1,

   &MIBNODE_mqxConfigInlineMacros,
   NULL,
   &MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxCPUAddressing = {
   3,

   NULL,
   NULL,
   &MIBNODE_mqxCPU,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxRevPSP = {
   2,

   &MIBNODE_mqxRevIO,
   NULL,
   &MIBNODE_mqxRevision,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqxRevision = {
   2,

   &MIBNODE_mqxCopyright,
   &MIBNODE_mqxRevKernel,
   &MIBNODE_mqxKernel,

   0,
   NULL,
   MIB_instance_zero, ASN1_TYPE_SEQUENCE,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};

RTCSMIB_NODE MIBNODE_mqx = {
   1,

   NULL,
   &MIBNODE_mqxKernel,
   &MIBNODE_psti,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxIOCIO = {
   1,

   &MIBNODE_mqxIOCRTCS,
   NULL,
   &MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxIOC = {
   4,

   NULL,
   &MIBNODE_mqxIOCIO,
   &MIBNODE_mqx,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxComponentMessage = {
   8,

   &MIBNODE_mqxComponentPart,
   NULL,
   &MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxComponentWatchdog = {
   7,

   &MIBNODE_mqxComponentMessage,
   NULL,
   &MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxComponentEvent = {
   3,

   &MIBNODE_mqxComponentMutex,
   NULL,
   &MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxComponentName = {
   1,

   &MIBNODE_mqxComponentSem,
   NULL,
   &MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, 0, {0}, NULL
};

RTCSMIB_NODE MIBNODE_mqxRevIO = {
   3,

   &MIBNODE_mqxRevBSP,
   NULL,
   &MIBNODE_mqxRevision,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   RTCSMIB_NODETYPE_INT_CONST, {0},
   NULL
};


boolean MIB_instance_mqxTaskEntry
   (
      RTCSMIB_WALK_PTR     mib,
      uint_32              op,
      boolean (_CODE_PTR_  find)(uint_32, pointer, pointer _PTR_),
      boolean _PTR_        found,
      pointer _PTR_        instance
   )
{ /* Body */
   struct {
      uint_32 mqxTaskID;
   } index;

   *found = FALSE;
   *instance = NULL;

   switch (op) {

   case RTCSMIB_OP_GET:
   case RTCSMIB_OP_SET:

      if (mib->inlen == 0) break;
      if (!RTCSMIB_id_read32(mib, &index.mqxTaskID)) return FALSE;
      if (mib->inlen != 0) break;
      *found = find(op, &index, instance);
      break;

   case RTCSMIB_OP_GETNEXT:
      if (mib->inlen == 0) {
         index.mqxTaskID = 0;
      } else {
         if (!RTCSMIB_id_read32(mib, &index.mqxTaskID)) return FALSE;
         index.mqxTaskID++;
      } /* Endif */
      *found = find(op, &index, instance);
      break;

   case RTCSMIB_OP_GETFIRST:
      index.mqxTaskID = 0;
      *found = find(RTCSMIB_OP_GETNEXT, &index, instance);
      break;
   } /* Endswitch */

   if (*found && (op != RTCSMIB_OP_SET)) {
      if (!RTCSMIB_id_write32 (mib, index.mqxTaskID)) return FALSE;
   } /* Endif */

   return TRUE;
} /* Endbody */



#include <stdlib.h>
#include <stddef.h>
#if (MQX_VERSION >= 250)
#include <mem_prv.h>
#include <mqx_prv.h>
#include <gen_rev.h>
#include <psp_rev.h>
#else
#include <mqx_prv.h>
#endif

extern RTCSMIB_NODE MIBNODE_sysObjectID;

boolean MIB_find_mqxTaskEntry
   (
      uint_32        op,
      pointer        index,
      pointer _PTR_  instance
   )
{ /* Body */
   KERNEL_DATA_STRUCT_PTR  kd_ptr = _mqx_get_kernel_data();
   _task_id                tid = (_task_id)*(uint_32_ptr)index;
   TD_STRUCT_PTR           td_ptr = NULL;

   if (op == RTCSMIB_OP_GET) {
      *instance = _task_get_td(tid);
      return (*instance != NULL);
   } /* Endif */

#if (MQX_VERSION >= 240) && (MQX_VERSION < 250)

   { /* Scope */
      TD_POOL_STRUCT_PTR      pool_ptr = (TD_POOL_STRUCT_PTR)&kd_ptr->TD_POOL;
      uint_32                 procnum, tasknum;

      procnum = PROC_NUMBER_FROM_TASKID(tid);
      if (procnum < kd_ptr->PROCESSOR_NUMBER) {
         tasknum = 1;
      } else if (procnum == kd_ptr->PROCESSOR_NUMBER) {
         tasknum = TASK_NUMBER_FROM_TASKID(tid);
         if (tasknum == 0) tasknum = 1;
      } else {
         pool_ptr = NULL;
      } /* Endif */

      for (;;) {
         if (pool_ptr == NULL) {
            break;
         } /* Endif */
         if (tasknum < TD_POOL_SIZE) {
            td_ptr = &pool_ptr->POOL[tasknum];
            break;
         } /* Endif */
         pool_ptr = pool_ptr->NEXT_TD_POOL;
         tasknum -= TD_POOL_SIZE;
      } /* Endfor */

      for (;;) {
         if (td_ptr == NULL) break;
         if (td_ptr->TASK_ID != 0) break;
         tasknum++;
         if (tasknum < TD_POOL_SIZE) {
            td_ptr++;
         } else {
            pool_ptr = pool_ptr->NEXT_TD_POOL;
            if (pool_ptr == NULL) {
               td_ptr = NULL;
               break;
            } /* Endif */
            td_ptr = &pool_ptr->POOL[0];
            tasknum = 0;
         } /* Endif */
      } /* Endfor */

   } /* Endscope */

#elif (MQX_VERSION >= 250)

   { /* Scope */
      QUEUE_ELEMENT_STRUCT_PTR search_ptr;
      uint_32                  td_num;

      search_ptr = kd_ptr->TD_LIST.NEXT;
      td_num = 0;
      for (;;) {
         td_ptr = (TD_STRUCT_PTR)((char_ptr)search_ptr - offsetof(TD_STRUCT, TD_LIST_INFO));
         if (td_ptr->TASK_ID >= tid) {
            break;
         } /* Endif */
         td_num++;
         if (td_num >= kd_ptr->TD_LIST.SIZE) {
            td_ptr = NULL;
            break;
         } /* Endif */
         search_ptr = search_ptr->NEXT;
      } /* Endfor */

   } /* Endscope */

#endif

   if (!td_ptr) {
      return FALSE;
   } /* Endif */

   *(uint_32_ptr)index = td_ptr->TASK_ID;
   *instance = td_ptr;
   return (td_ptr != NULL);

} /* Endbody */

uint_32   MIB_get_mqxTaskID                     (pointer td) {return ((TD_STRUCT_PTR)td)->TASK_ID;}
#if (MQX_VERSION >= 240) && (MQX_VERSION < 250)
uint_32   MIB_get_mqxTaskCreator                (pointer td) {return ((TD_STRUCT_PTR)td)->FATHER;}
uint_32   MIB_get_mqxTaskSchedTimeSlice         (pointer td) {return ((TD_STRUCT_PTR)td)->TIME_SLICE;}
#elif (MQX_VERSION >= 250)
uint_32   MIB_get_mqxTaskCreator                (pointer td) {return ((TD_STRUCT_PTR)td)->PARENT;}
uint_32   MIB_get_mqxTaskSchedTimeSlice         (pointer td) {uint_32 ms; _sched_get_rr_interval(((TD_STRUCT_PTR)td)->TASK_ID,&ms); return ms;}
#endif
uchar_ptr MIB_get_mqxTaskName                   (pointer td) {return (uchar_ptr)((TD_STRUCT_PTR)td)->TASK_TEMPLATE_PTR->TASK_NAME;}
uint_32   MIB_get_mqxTaskState                  (pointer td) {return ((TD_STRUCT_PTR)td)->STATE;}
uint_32   MIB_get_mqxTaskErrorCode              (pointer td) {return ((TD_STRUCT_PTR)td)->TASK_ERROR_CODE;}
uint_32   MIB_get_mqxTaskSchedPriority          (pointer td) {return ((TD_STRUCT_PTR)td)->MY_QUEUE->PRIORITY;}
uint_32   MIB_get_mqxTaskSchedHomePriority      (pointer td) {return ((TD_STRUCT_PTR)td)->HOME_QUEUE->PRIORITY;}
uint_32   MIB_get_mqxTaskSchedPolicy            (pointer td) {return (((TD_STRUCT_PTR)td)->FLAGS & MQX_TIME_SLICE_TASK) ? MQX_SCHED_RR : MQX_SCHED_FIFO;}
uint_32   MIB_get_mqxTaskStackSize              (pointer td) {uint_32 ss,su; _klog_get_task_stack_usage(((TD_STRUCT_PTR)td)->TASK_ID,&ss,&su); return ss;}
uint_32   MIB_get_mqxTaskStackUsed              (pointer td) {uint_32 ss,su; _klog_get_task_stack_usage(((TD_STRUCT_PTR)td)->TASK_ID,&ss,&su); return su;}
uchar_ptr MIB_get_mqxTaskIOstdin                (pointer td) {return (((TD_STRUCT_PTR)td)->STDIN_STREAM)  ? (uchar_ptr)((FILE_PTR)((TD_STRUCT_PTR)td)->STDIN_STREAM)->DEV_PTR->IDENTIFIER  : NULL;}
uchar_ptr MIB_get_mqxTaskIOstdout               (pointer td) {return (((TD_STRUCT_PTR)td)->STDOUT_STREAM) ? (uchar_ptr)((FILE_PTR)((TD_STRUCT_PTR)td)->STDOUT_STREAM)->DEV_PTR->IDENTIFIER : NULL;}
uchar_ptr MIB_get_mqxTaskIOstderr               (pointer td) {return (((TD_STRUCT_PTR)td)->STDERR_STREAM) ? (uchar_ptr)((FILE_PTR)((TD_STRUCT_PTR)td)->STDERR_STREAM)->DEV_PTR->IDENTIFIER : NULL;}
uint_32   MIB_get_mqxTaskFlagFloatingPoint      (pointer td) {return (((TD_STRUCT_PTR)td)->FLAGS & MQX_FLOATING_POINT_TASK)  ? 1 : 0;}
uint_32   MIB_get_mqxTaskFlagLoggingEnabled     (pointer td) {return (((TD_STRUCT_PTR)td)->FLAGS & TASK_LOGGING_ENABLED)     ? 1 : 0;}
uint_32   MIB_get_mqxTaskFlagWatchdogEnabled    (pointer td) {return (((TD_STRUCT_PTR)td)->FLAGS & TASK_WATCHDOG_STARTED)    ? 1 : 0;}
uint_32   MIB_get_mqxTaskFlagPreemptionDisabled (pointer td) {return (((TD_STRUCT_PTR)td)->FLAGS & TASK_PREEMPTION_DISABLED) ? 1 : 0;}


void MIBMQX_init(void)
{ /* Body */
   KERNEL_DATA_STRUCT_PTR kd_ptr = _mqx_get_kernel_data();

/* CR 850 */
#define MIB_set_const(var,val) \
   MIBNODE_ ## var.TYPE = RTCSMIB_NODETYPE_UINT_CONST; \
   MIBNODE_ ## var.GET.UINT_CONST = val

#define MIB_set_ptr(var,type,ptr) \
   MIBNODE_ ## var.TYPE = RTCSMIB_NODETYPE_ ## type ## _PTR; \
   MIBNODE_ ## var.GET.type ## _PTR = ptr

#define MIB_set_fn(var,type) \
   MIBNODE_ ## var.TYPE = RTCSMIB_NODETYPE_ ## type ## _FN; \
   MIBNODE_ ## var.GET.type ## _FN = MIB_get_ ## var

   MIB_set_ptr(   sysObjectID, OID, &MIBNODE_mqx );

   MIB_set_const( mqxVersion,       MQX_VERSION );
#if (MQX_VERSION >= 250)
   MIB_set_const( mqxRevKernel,     GEN_REVISION            );
   MIB_set_const( mqxRevPSP,        PSP_REVISION            );
   MIB_set_const( mqxRevIO,         atoi(_mqx_io_revision)  );
   MIB_set_const( mqxRevBSP,        atoi(_mqx_bsp_revision) );
#endif
   MIB_set_ptr(   mqxCopyright,     DISPSTR, (uchar_ptr)_mqx_copyright           );
   MIB_set_ptr(   mqxDate,          DISPSTR, (uchar_ptr)_mqx_date                );
   MIB_set_const( mqxCPUType,       MQX_CPU                                      );
   MIB_set_const( mqxCPUEndian,     PSP_ENDIAN                                   );
   MIB_set_const( mqxCPUAddressing, PSP_MEMORY_ADDRESSING_CAPABILITY             );
   MIB_set_ptr(   mqxProcessorNum,  UINT, (uint_32_ptr)&kd_ptr->PROCESSOR_NUMBER );

   MIB_set_const( mqxConfigFloatingPointIO,      MQX_INCLUDE_FLOATING_POINT_IO        );
   MIB_set_const( mqxConfigInlineMacros,         MQX_USE_INLINE_MACROS                );
   MIB_set_const( mqxConfigKernelLogging,        MQX_KERNEL_LOGGING                   );
   MIB_set_const( mqxConfigMonitorStack,         MQX_MONITOR_STACK                    );
   MIB_set_const( mqxConfigTaskCreationBlocks,   MQX_TASK_CREATION_BLOCKS             );
   MIB_set_const( mqxConfigTaskDestruction,      MQX_TASK_DESTRUCTION                 );
   MIB_set_const( mqxConfigComponentDestruction, MQX_COMPONENT_DESTRUCTION            );
   MIB_set_const( mqxConfigCheckErrors,          MQX_CHECK_ERRORS                     );
   MIB_set_const( mqxConfigCheckValidity,        MQX_CHECK_VALIDITY                   );
   MIB_set_const( mqxConfigCheckAlloc,           MQX_CHECK_MEMORY_ALLOCATION_ERRORS   );
#if (MQX_VERSION >= 240) && (MQX_VERSION < 250)
   MIB_set_const( mqxConfig64BitInts,            MQX_COMPILER_SUPPORTS_64_BIT_NUMBERS );
#elif (MQX_VERSION >= 250)
   MIB_set_const( mqxConfig32BitQIDs,            MQX_USE_32BIT_MESSAGE_QIDS           );
#endif

   MIB_set_fn(    mqxTaskID,                     UINT    );
   MIB_set_fn(    mqxTaskCreator,                UINT    );
   MIB_set_fn(    mqxTaskName,                   DISPSTR );
   MIB_set_fn(    mqxTaskState,                  UINT    );
   MIB_set_fn(    mqxTaskErrorCode,              UINT    );
   MIB_set_fn(    mqxTaskSchedPriority,          UINT    );
   MIB_set_fn(    mqxTaskSchedHomePriority,      UINT    );
   MIB_set_fn(    mqxTaskSchedPolicy,            UINT    );
   MIB_set_fn(    mqxTaskSchedTimeSlice,         UINT    );
   MIB_set_fn(    mqxTaskStackSize,              UINT    );
   MIB_set_fn(    mqxTaskStackUsed,              UINT    );
   MIB_set_fn(    mqxTaskIOstdin,                DISPSTR );
   MIB_set_fn(    mqxTaskIOstdout,               DISPSTR );
   MIB_set_fn(    mqxTaskIOstderr,               DISPSTR );
   MIB_set_fn(    mqxTaskFlagFloatingPoint,      UINT    );
   MIB_set_fn(    mqxTaskFlagLoggingEnabled,     UINT    );
   MIB_set_fn(    mqxTaskFlagWatchdogEnabled,    UINT    );
   MIB_set_fn(    mqxTaskFlagPreemptionDisabled, UINT    );
/* End CR 850 */

   RTCSMIB_mib_add(&MIBNODE_psti);

} /* Endbody */

/* EOF */
